name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  asset:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: .github/workflows/create_assets.sh ${{ github.ref_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: tvg-*
